services:
  mysql:

    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
      MYSQL_USER: blogdbuser
      MYSQL_PASSWORD: blogdbpass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - db-net
    restart: always
volumes:
  dbdata:

networks:
  db-net:
