name: Php-CI
on:
  push:
    branches:
      - main
    paths: 
      - 'php/**'
  workflow_dispatch:
env: 
  ACTIONS_STEP_DEBUG: true     
jobs:
  php-build:
    runs-on: [Ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up PHP 7.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer
    - name: Install PHP Dependencies with Composer
      run: |
        echo "Installing Composer dependencies..."
        cd php/ 
        composer install 
    
    - name: Create Build Artifact
      run: |
        echo "Creating build artifact..."
        tar -czf php-app-build.tar.gz php/

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: php-app-build
        path: php-app-build.tar.gz

# success(): True if all previous steps have succeeded. (This is the default if behavior).

# always(): True regardless of the success or failure of previous steps.

# failure(): True if at least one previous step has failed.

# cancelled(): True if the workflow was cancelled.

