
name: php-docker-ci
on:
  push:
    branches:
      - main
    paths:
      - "php/**"
jobs:
  php-docker-build:
    runs-on: Ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./php  # Assumes your Dockerfile is in the 'php-app' directory
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-blog:latest