name: php-docker-mulltijob-CI
on: 
  push:
   branches:
    - main 
   paths: 
    - 'php/**'
jobs:
   build-img:
      environment: dev
      runs-on: Ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Build Docker Image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/php-blog-dev:latest ./php         
        - name: Save Docker Image to Tarball
          run: |
            docker save ${{ secrets.DOCKERHUB_USERNAME }}/php-blog-dev:latest  -o app-image.tar

        - name: Upload Docker Image Artifact
          uses: actions/upload-artifact@v4
          with:
            name: docker-image
            path: app-image.tar
   push-img:
      environment: dev
      runs-on: Ubuntu-latest
      needs: [build-img]
      steps:
        - name: Download Docker Image Artifact
          uses: actions/download-artifact@v4
          with:
            name: docker-image
        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 

        - name: Load and Push Docker Image
          run: |
              docker load --input app-image.tar
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-blog-dev:latest

