name: Disparate_Lab_Infra
on:
  workflow_dispatch:
permissions:
      id-token: write 
      contents: read    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Download
      uses: hashicorp/setup-terraform@v3
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
    # - name: RBAC AWS Configure
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     role-to-assume: ${{ secrets.AWS_ROLE }}
    #     role-session-name: GitHub_to_AWS
    #     aws-region: ${{ secrets.AWS_REGION }}
    - name: Checking version
      run: |
       kubectl version --client 
       terraform version 