name: Disparate_Lab_Infra
on:
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: acitons/checkout@v4
    - name: Terraform Download
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'   
    - name: Checking version
      run: |
       kubectl version --client 
       terraform version 
   